<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\shijian77]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[shijian77]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:56]]></Time>
<TimeTick>1472034656</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://newtours.demoaut.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:56]]></Time>
<TimeTick>1472034656</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="0" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:57]]></Time>
<TimeTick>1472034657</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["york.yu"]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:57]]></Time>
<TimeTick>1472034657</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" Source="Action1" SourceLine="0" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["57bd770bb5250f7784bb375ea311d9c249a4004c850f9c24"]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:57]]></Time>
<TimeTick>1472034657</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/8/24 - 18:30:57]]></Time>
<TimeTick>1472034657</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:18]]></Time>
<TimeTick>1472034678</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D).Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:18]]></Time>
<TimeTick>1472034678</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="26" status="Warning" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D).Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "不再保存密码(D)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:18]]></Time>
<TimeTick>1472034678</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:18]]></Time>
<TimeTick>1472034678</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="28" status="Warning" nType="Parent description" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="27" status="Failed" nType="Run Error" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="25" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Failed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;不再保存密码(D)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (4): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinCheckBox(&quot;不再保存密码(D)&quot;).Set &quot;ON&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:18]]></Time>
<TimeTick>1472034678</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="29" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D).Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" status="Warning" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D).Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "不再保存密码(D)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="39" status="Warning" nType="Parent description" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="38" status="Failed" nType="Run Error" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="36" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="35" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;不再保存密码(D)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (4): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinCheckBox(&quot;不再保存密码(D)&quot;).Set &quot;ON&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:31:58]]></Time>
<TimeTick>1472034718</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="40" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D).Set]]></Obj>
<Details plainTxt="False" ><![CDATA["OFF"]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" status="Warning" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D).Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "不再保存密码(D)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="50" status="Warning" nType="Parent description" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="49" status="Failed" nType="Run Error" Source="Action1" SourceLine="3" >
<Disp><![CDATA[不再保存密码(D)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="47" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="46" status="Failed" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;不再保存密码(D)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (5): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinCheckBox(&quot;不再保存密码(D)&quot;).Set &quot;OFF&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:35:54]]></Time>
<TimeTick>1472034954</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="51" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D).Set]]></Obj>
<Details plainTxt="False" ><![CDATA["OFF"]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="59" status="Warning" Source="Action1" SourceLine="4" >
<Disp><![CDATA[不再保存密码(D).Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "不再保存密码(D)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="61" status="Warning" nType="Parent description" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="60" status="Failed" nType="Run Error" Source="Action1" SourceLine="4" >
<Disp><![CDATA[不再保存密码(D)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="58" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="57" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;不再保存密码(D)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (5): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinCheckBox(&quot;不再保存密码(D)&quot;).Set &quot;OFF&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:18]]></Time>
<TimeTick>1472034978</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="62" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D).Set]]></Obj>
<Details plainTxt="False" ><![CDATA["OFF"]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" status="Warning" Source="Action1" SourceLine="4" >
<Disp><![CDATA[不再保存密码(D).Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[不再保存密码(D)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "不再保存密码(D)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="72" status="Warning" nType="Parent description" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="71" status="Failed" nType="Run Error" Source="Action1" SourceLine="4" >
<Disp><![CDATA[不再保存密码(D)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="69" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="68" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;不再保存密码(D)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (5): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinCheckBox(&quot;不再保存密码(D)&quot;).Set &quot;OFF&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:36:55]]></Time>
<TimeTick>1472035015</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="73" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[否(N).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="81" status="Warning" Source="Action1" SourceLine="4" >
<Disp><![CDATA[否(N).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[否(N)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "否(N)" object's parent "自动完成密码" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[自动完成密码]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = 自动完成密码<br>Native Class = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="83" status="Warning" nType="Parent description" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="82" status="Failed" nType="Run Error" Source="Action1" SourceLine="4" >
<Disp><![CDATA[否(N)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="80" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[自动完成密码]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="79" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;否(N)&quot; object's parent &quot;自动完成密码&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (6): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Dialog(&quot;自动完成密码&quot;).WinButton(&quot;否(N)&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:18]]></Time>
<TimeTick>1472035038</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" status="Failed" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:34]]></Time>
<TimeTick>1472035054</TimeTick>
<NodeArgs eType="General" icon="14" nRep="85" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/8/24 - 18:30:56" eTime="2016/8/24 - 18:37:34" passed="0" failed="12" warnings="12" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[shijian77 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/8/24 - 18:37:34]]></Time>
<TimeTick>1472035054</TimeTick>
<NodeArgs eType="General" icon="15" nRep="88" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/8/24 - 18:30:53" eTime="2016/8/24 - 18:37:34" passed="0" failed="12" warnings="12" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test shijian77 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>